### ISSUE TITLE
Google sign in problem

### ISSUE THREAD

**Issue by sispus** [intersimone999/pyqtws#16] opened 2020-12-06 10:31 UTC
I'm using netflix effecttively and liked silos. Thank you. Want to use google docs. 
I cannot sign in to google apps. It says:

> This browser may not be secure.[ Learn more](https://support.google.com/accounts/answer/7675428?hl=en)
> Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.

I have already allowed "less secure apps". 
I think this is relevant: 
https://security.googleblog.com/2019/04/better-protection-against-man-in-middle.html

Is there a way to fix it?

**Comment by intersimone999** [comment] 2020-12-07 10:18
Most likely it depends on your version of qt5-webengine. I'm using 5.15.2 and I can't reproduce this issue.

**Comment by sispus** [comment] 2020-12-07 10:32
I'm using 5.15.2.1 
other info:
```
Operating System: Manjaro Linux
KDE Plasma Version: 5.20.4
KDE Frameworks Version: 5.76.0
Qt Version: 5.15.2
Kernel Version: 5.9.11-3-MANJARO
OS Type: 64-bit
Processors: 4 × Intel® Core™ i5-3317U CPU @ 1.70GHz
Memory: 3,7 GiB of RAM
Graphics Processor: Mesa DRI Intel® HD Graphics 4000
```
By the way, with the last updates Silos URL Opener starts to open Firefox to reach each silo. Individual Silo needs me to allow xdg-open to initiate it by Firefox. Starting the silo from menu (without URL Opener) no need for Firefox. Is it normal or related with my issue?

**Comment by riptide981** [comment] 2020-12-07 19:46
I have the same problem in Stadia.

Allowed "less secure apps" not active as i use 2FA.

qt5-webengine: 5.15.2

```
 OS: Manjaro 20.2 Nibia
 Kernel: x86_64 Linux 5.9.11-3-MANJARO
 Uptime: 1h 42m
 Packages: 1319
 Shell: bash 5.0.18
 Resolution: 3600x1080
 DE: KDE 5.76.0 / Plasma 5.20.4
 WM: KWin
 GTK Theme: Breath-Dark [GTK2/3]
 Icon Theme: breath2-dark
 Disk: 296G / 520G (58%)
 CPU: AMD Phenom II X6 1090T @ 6x 3.2GHz
 GPU: NV92
 RAM: 3918MiB / 7957MiB
```

**Comment by intersimone999** [comment] 2020-12-08 16:02
I use 2FA as well (no "less secure apps"), but everything works fine, in my case (ArchLinux). Is this happening only with Manjaro? Is it reproducible also with other distributions?

**Comment by intersimone999** [comment] 2020-12-08 16:05
@sispus please open another issue for your problem with Silos URL Opener, I think it is unrelated to this.

**Comment by tbrasser** [comment] 2020-12-14 19:04
I encounter this issue with Arch and Chromium 87.0.4280.88-1

**Comment by sispus** [comment] 2021-01-15 22:04
I just tried to create a new google account from the silo window. I can create and use this new account successfully. But I cannot use any other account.

**Comment by intersimone999** [comment] 2021-01-23 10:37
With a different Google account I could reproduce the issue. However, I got the same error for that account by using Falkon, which is based on QTWebEngine, like silos. The problem is probably due to the fact that QTWebEngine is based on a version of Chromium that Google considers insecure, like [this Reddit post](https://www.reddit.com/r/programming/comments/eamnk6/google_services_blocking_unsecure_web_browsers/), based on [this article](https://www.bleepingcomputer.com/news/google/google-now-bans-some-linux-web-browsers-from-their-services/), mentions.
The best thing to do is probably reporting the bug for QTWebEngine. I am closing this for now since it can not be fixed in silos, as far as I know.

A possible workaround is using the ChangeUserAgent plugin (like for WhatsApp), as mentioned [here](https://www.reddit.com/r/linux/comments/eah6z5/google_now_bans_some_linux_web_browsers_from/fard0s2?utm_source=share&utm_medium=web2x&context=3); if you want you can test it and open a pull request on the repo with the all the apps: (https://github.com/intersimone999/silos-apps)[https://github.com/intersimone999/silos-apps].

**Closed by intersimone999** 2021-01-23 10:37 UTC
